CREATE OR REPLACE FORCE VIEW V_SIM_TABLA_AMORT_CONCEPTO ("CVE_GPO_EMPRESA", "CVE_EMPRESA", "ID_PRESTAMO", "NUM_PAGO_AMORTIZACION", "FECHA_AMORTIZACION", "ID_ACCESORIO", "IMP_NETO", "IMP_ORIGINAL", "IMP_EXTRAORDINARIO", "IMP_PAGADO", "CVE_CONCEPTO")
AS
  (SELECT T.CVE_GPO_EMPRESA,
    T.CVE_EMPRESA,
    T.ID_PRESTAMO,
    T.NUM_PAGO_AMORTIZACION,
    T.FECHA_AMORTIZACION,
    C.ID_ACCESORIO,
    CASE
      WHEN C.CVE_CONCEPTO = 'CAPITA'
      THEN ROUND( (NVL(T.IMP_CAPITAL_AMORT,0) + NVL(T.IMP_EXT_CAPITAL_AMORT,0) - NVL(T.IMP_CAPITAL_AMORT_PAGADO,0)) *-1,2)
      WHEN C.CVE_CONCEPTO = 'INTERE'
      THEN ROUND( (NVL(T.IMP_INTERES,0) + NVL(T.IMP_EXT_INTERES,0) - NVL(T.IMP_INTERES_PAGADO,0)) *-1,2)
      WHEN C.CVE_CONCEPTO = 'IVAINT'
      THEN ROUND( (NVL(T.IMP_IVA_INTERES,0) + NVL(T.IMP_EXT_IVA_INTERES,0) - NVL(T.IMP_IVA_INTERES_PAGADO,0)) *-1,2)
      WHEN C.CVE_CONCEPTO = 'INTEXT'
      THEN ROUND( (NVL(T.IMP_INTERES_EXTRA,0) + NVL(T.IMP_EXT_INTERES_EXTRA,0) - NVL(T.IMP_INTERES_EXTRA_PAGADO,0)) *-1,2)
      WHEN C.CVE_CONCEPTO = 'IVAINTEX'
      THEN ROUND( (NVL(T.IMP_IVA_INTERES_EXTRA,0) + NVL(T.IMP_EXT_IVA_INTERES_EXTRA,0) - NVL(T.IMP_IVA_INTERES_EXTRA_PAGADO,0)) *-1,2)
      WHEN C.CVE_CONCEPTO = 'PAGOTARD'
      THEN ROUND( (NVL(T.IMP_PAGO_TARDIO,0) + NVL(T.IMP_EXT_PAGO_TARDIO,0) - NVL(T.IMP_PAGO_TARDIO_PAGADO,0)) *-1,2)
      WHEN C.CVE_CONCEPTO = 'GESCOB'
      THEN ROUND( (NVL(T.IMP_EXT_GESTION_COBRANZA,0) - NVL(T.IMP_GESTION_COBRANZA_PAGADO,0)) *-1,2)
      WHEN C.CVE_CONCEPTO = 'INTMORA'
      THEN ROUND( (NVL(T.IMP_INTERES_MORA,0) + NVL(T.IMP_EXT_INTERES_MORA,0) - NVL(T.IMP_INTERES_MORA_PAGADO,0)) *-1,2)
      WHEN C.CVE_CONCEPTO = 'IVAINTMO'
      THEN ROUND( (NVL(T.IMP_IVA_INTERES_MORA,0) + NVL(T.IMP_EXT_IVA_INTERES_MORA,0) - NVL(T.IMP_IVA_INTERES_MORA_PAGADO,0)) *-1,2)
    END AS IMP_NETO,
    CASE
      WHEN C.CVE_CONCEPTO = 'CAPITA'
      THEN ROUND( NVL(T.IMP_CAPITAL_AMORT,0) * -1, 2)
      WHEN C.CVE_CONCEPTO = 'INTERE'
      THEN ROUND( NVL(T.IMP_INTERES,0) *-1,2)
      WHEN C.CVE_CONCEPTO = 'IVAINT'
      THEN ROUND( NVL(T.IMP_IVA_INTERES,0) *-1,2)
      WHEN C.CVE_CONCEPTO = 'INTEXT'
      THEN ROUND( NVL(T.IMP_INTERES_EXTRA,0) *-1,2)
      WHEN C.CVE_CONCEPTO = 'IVAINTEX'
      THEN ROUND( NVL(T.IMP_IVA_INTERES_EXTRA,0) *-1,2)
      WHEN C.CVE_CONCEPTO = 'PAGOTARD'
      THEN ROUND( NVL(T.IMP_PAGO_TARDIO,0) *-1,2)
      WHEN C.CVE_CONCEPTO = 'GESCOB'
      THEN 0
      WHEN C.CVE_CONCEPTO = 'INTMORA'
      THEN ROUND( NVL(T.IMP_INTERES_MORA,0) *-1,2)
      WHEN C.CVE_CONCEPTO = 'IVAINTMO'
      THEN ROUND( NVL(T.IMP_IVA_INTERES_MORA,0) *-1,2)
    END AS IMP_ORIGINAL,
    CASE
      WHEN C.CVE_CONCEPTO = 'CAPITA'
      THEN ROUND( NVL(T.IMP_EXT_CAPITAL_AMORT,0) * -1, 2)
      WHEN C.CVE_CONCEPTO = 'INTERE'
      THEN ROUND( NVL(T.IMP_EXT_INTERES,0) *-1,2)
      WHEN C.CVE_CONCEPTO = 'IVAINT'
      THEN ROUND( NVL(T.IMP_EXT_IVA_INTERES,0) *-1,2)
      WHEN C.CVE_CONCEPTO = 'INTEXT'
      THEN ROUND( NVL(T.IMP_EXT_INTERES_EXTRA,0) *-1,2)
      WHEN C.CVE_CONCEPTO = 'IVAINTEX'
      THEN ROUND( NVL(T.IMP_EXT_IVA_INTERES_EXTRA,0) *-1,2)
      WHEN C.CVE_CONCEPTO = 'PAGOTARD'
      THEN ROUND( NVL(T.IMP_EXT_PAGO_TARDIO,0) *-1,2)
      WHEN C.CVE_CONCEPTO = 'GESCOB'
      THEN ROUND( NVL(T.IMP_EXT_GESTION_COBRANZA,0) *-1,2)
      WHEN C.CVE_CONCEPTO = 'INTMORA'
      THEN ROUND( NVL(T.IMP_EXT_INTERES_MORA,0) *-1,2)
      WHEN C.CVE_CONCEPTO = 'IVAINTMO'
      THEN ROUND( NVL(T.IMP_EXT_IVA_INTERES_MORA,0) *-1,2)
    END AS IMP_EXTRAORDINARIO,
    CASE
      WHEN C.CVE_CONCEPTO = 'CAPITA'
      THEN ROUND( NVL(T.IMP_CAPITAL_AMORT_PAGADO,0),2)
      WHEN C.CVE_CONCEPTO = 'INTERE'
      THEN ROUND( NVL(T.IMP_INTERES_PAGADO,0),2)
      WHEN C.CVE_CONCEPTO = 'IVAINT'
      THEN ROUND( NVL(T.IMP_IVA_INTERES_PAGADO,0),2)
      WHEN C.CVE_CONCEPTO = 'INTEXT'
      THEN ROUND( NVL(T.IMP_INTERES_EXTRA_PAGADO,0),2)
      WHEN C.CVE_CONCEPTO = 'IVAINTEX'
      THEN ROUND( NVL(T.IMP_IVA_INTERES_EXTRA_PAGADO,0),2)
      WHEN C.CVE_CONCEPTO = 'PAGOTARD'
      THEN ROUND( NVL(T.IMP_PAGO_TARDIO_PAGADO,0),2)
      WHEN C.CVE_CONCEPTO = 'GESCOB'
      THEN ROUND( NVL(T.IMP_GESTION_COBRANZA_PAGADO,0),2)
      WHEN C.CVE_CONCEPTO = 'INTMORA'
      THEN ROUND( NVL(T.IMP_INTERES_MORA_PAGADO,0),2)
      WHEN C.CVE_CONCEPTO = 'IVAINTMO'
      THEN ROUND( NVL(T.IMP_IVA_INTERES_MORA_PAGADO,0),2)
    END AS IMP_PAGADO,
    C.CVE_CONCEPTO
  FROM SIM_TABLA_AMORTIZACION T,
    PFIN_CAT_CONCEPTO C
  WHERE T.CVE_GPO_EMPRESA = C.CVE_GPO_EMPRESA
  AND T.CVE_EMPRESA       = C.CVE_EMPRESA
  AND C.CVE_CONCEPTO     IN ('CAPITA', 'INTERE', 'IVAINT', 'INTEXT', 'IVAINTEX', 'PAGOTARD', 'GESCOB', 'INTMORA','IVAINTMO')
  UNION ALL
  -- Obtiene el importe de accesorios que apliquen para el préstamo
  SELECT T.CVE_GPO_EMPRESA,
    T.CVE_EMPRESA,
    T.ID_PRESTAMO,
    T.NUM_PAGO_AMORTIZACION,
    T.FECHA_AMORTIZACION,
    A.ID_ACCESORIO,
    ROUND( (IMP_ACCESORIO           + NVL(IMP_EXT_ACCESORIO,0) - NVL(IMP_ACCESORIO_PAGADO,0)) * -1,2) AS IMP_NETO,
    ROUND( IMP_ACCESORIO            * -1,2)                                                           AS IMP_ORIGINAL,
    ROUND( NVL(IMP_EXT_ACCESORIO,0) * -1,2)                                                           AS IMP_EXTRAORDINARIO,
    ROUND( NVL(IMP_ACCESORIO_PAGADO,0),2)                                                             AS IMP_PAGADO,
    D.CVE_CONCEPTO
  FROM SIM_TABLA_AMORTIZACION T,
    SIM_TABLA_AMORT_ACCESORIO A,
    SIM_CAT_ACCESORIO C,
    PFIN_CAT_CONCEPTO D
  WHERE T.CVE_GPO_EMPRESA     = A.CVE_GPO_EMPRESA
  AND T.CVE_EMPRESA           = A.CVE_EMPRESA
  AND T.ID_PRESTAMO           = A.ID_PRESTAMO
  AND T.NUM_PAGO_AMORTIZACION = A.NUM_PAGO_AMORTIZACION
  AND A.CVE_GPO_EMPRESA       = C.CVE_GPO_EMPRESA
  AND A.CVE_EMPRESA           = C.CVE_EMPRESA
  AND A.ID_ACCESORIO          = C.ID_ACCESORIO
  AND A.CVE_GPO_EMPRESA       = D.CVE_GPO_EMPRESA
  AND A.CVE_EMPRESA           = D.CVE_EMPRESA
  AND A.ID_ACCESORIO          = D.ID_ACCESORIO
  );